//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHCHIEU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LICHCHIEU()
        {
            this.QUANLYVEs = new HashSet<QUANLYVE>();
        }
    
        public int MARAP { get; set; }
        public int MASUAT { get; set; }
        public Nullable<int> MAPHIM { get; set; }
    
        public virtual PHIM PHIM { get; set; }
        public virtual RAP RAP { get; set; }
        public virtual SUATCHIEU SUATCHIEU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUANLYVE> QUANLYVEs { get; set; }
    }
}
